### ISSUE TITLE
No artifacts were found

### ISSUE THREAD

**Issue by conkyliu** [lencx/OhMyBox#19]
<img width="330" alt="image" src="https://user-images.githubusercontent.com/26617741/190890176-848ab07c-aed7-48ca-96ad-268fa0e95929.png">
同样的配置，这是什么错误呢。

**Comment by lencx** [comment]
从报错信息来看，预期路径下的资源并不存在，所以 action 并未触发构建行为（`tauri build`），可以尝试排查 `package.json -> scripts` 中的命令是否改动了，导致 action 执行并未触发 `tauri build`。或者尝试修改 action 中的 yaml 文件，主动去执行 `yarn tauri build` 命令。

**Comment by conkyliu** [comment]
> 从报错信息来看，预期路径下的资源并不存在，所以 action 并未触发构建行为（`tauri build`），可以尝试排查 `package.json -> scripts` 中的命令是否改动了，导致 action 执行并未触发 `tauri build`。或者尝试修改 action 中的 yaml 文件，主动去执行 `yarn tauri build` 命令。

好的，我再排查下！
